import 'package:flutter/material.dart';


void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Pm25(),
        ]),
      ),
    );
  }
}

class Pm25 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(image: DecorationImage(image: AssetImage("assets/images/background.jpg"),fit: BoxFit.cover)),
          child: Stack(
            children: [
              Positioned(
                left: -6,
                top: 0,
                child: Container(
                  width: 807.12,
                  height: 1211,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/807x1211"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 13,
                child: Container(
                  width: 357.96,
                  height: 27,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 289,
                        top: 3,
                        child: Container(
                          width: 22.16,
                          height: 17.62,
                          child: Stack(children: [
                          
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 332,
                        top: 5,
                        child: Container(
                          width: 25.96,
                          height: 15,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 23.65,
                                  height: 15,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1.30, color: Colors.white),
                                      borderRadius: BorderRadius.circular(3.26),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 24.23,
                                top: 3.26,
                                child: Container(
                                  width: 1.73,
                                  height: 7.83,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(0.65),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 256,
                        top: 5,
                        child: Container(
                          width: 13.80,
                          height: 15.50,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 10.74,
                                top: 0,
                                child: Container(
                                  width: 3.07,
                                  height: 15.50,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(1.38),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 7.16,
                                top: 2.70,
                                child: Container(
                                  width: 3.07,
                                  height: 12.80,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(1.38),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 3.58,
                                top: 6.74,
                                child: Container(
                                  width: 3.07,
                                  height: 8.76,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(1.38),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: -0,
                                top: 10.11,
                                child: Container(
                                  width: 3.07,
                                  height: 5.39,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(1.38),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          '10:55',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 18,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 227,
                child: Container(
                  width: 394,
                  height: 140,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 256,
                        top: 97,
                        child: SizedBox(
                          width: 103,
                          height: 26,
                          child: Text(
                            '(AQI-US)',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 271,
                        top: 46,
                        child: SizedBox(
                          width: 74,
                          height: 48,
                          child: Text(
                            '112',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 52.16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 19,
                        top: 33,
                        child: SizedBox(
                          width: 148,
                          height: 40.16,
                          child: Text(
                            'Bangkok',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 33.54,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        top: 81,
                        child: SizedBox(
                          width: 139,
                          height: 31,
                          child: Text(
                            'January 1 , 2:30',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 408,
                child: Container(
                  width: 394,
                  height: 140,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 256,
                        top: 97,
                        child: SizedBox(
                          width: 103,
                          height: 26,
                          child: Text(
                            '(AQI-US)',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 271,
                        top: 46,
                        child: SizedBox(
                          width: 74,
                          height: 48,
                          child: Text(
                            '67',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 52.16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 19,
                        top: 33,
                        child: SizedBox(
                          width: 294,
                          height: 40,
                          child: Text(
                            'Nakhon Pathom',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 30,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        top: 81,
                        child: SizedBox(
                          width: 179,
                          height: 31,
                          child: Text(
                            'January 24, 2:30',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 179,
                top: 52,
                child: Container(
                  width: 65.53,
                  height: 72.96,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 2.53,
                        top: 0,
                        child: Text(
                          'Blanc ',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 25.34,
                            fontFamily: 'Playfair Display',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 24.71,
                        top: 23.12,
                        child: Text(
                          'et',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 25.34,
                            fontFamily: 'Italianno',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 9.19,
                        top: 38.96,
                        child: Text(
                          'Noir',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 25.34,
                            fontFamily: 'Playfair Display',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 44.34,
                        top: 38.96,
                        child: Container(
                          width: 20.27,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 0.32,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 38.96,
                        child: Container(
                          width: 20.27,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 0.32,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -32,
                top: 66,
                child: Container(
                  width: 132,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 132,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Color(0xB2D9D9D9), 
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(30),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 79,
                        top: 7,
                        child: Container(
                          width: 35,
                          height: 35,
                          padding: const EdgeInsets.symmetric(horizontal: 4.38, vertical: 2.92),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(image: DecorationImage(image: AssetImage("assets/images/img_healthicons_ui.svg"),fit: BoxFit.cover)),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 26.25,
                                height: 29.17,
                                child: Stack(children: [
                                
                                ]),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 297,
                top: 69,
                child: Container(
                  width: 52,
                  height: 51,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 52,
                          height: 51,
                          decoration: ShapeDecoration(
                            color: Color(0xB2D9D9D9),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 6,
                        top: 6,
                        child: Container(
                          width: 40,
                          height: 40,
                          padding: const EdgeInsets.all(3.33),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 33.33,
                                height: 33.33,
                                child: Stack(children: [
                                
                                ]),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 359,
                top: 69,
                child: Container(
                  width: 52,
                  height: 51,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 52,
                          height: 51,
                          decoration: ShapeDecoration(
                            color: Color(0xB2D9D9D9),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 6,
                        top: 6,
                        child: Container(
                          width: 40,
                          height: 40,
                          padding: const EdgeInsets.only(
                            top: 6.67,
                            left: 3.33,
                            right: 1.95,
                            bottom: 5,
                          ),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                            
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 170,
                top: 157,
                child: Text(
                  'Pm 2.5',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 25,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w800,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 349,
                top: 817,
                child: Container(
                  width: 62,
                  height: 62,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 371,
                top: 836,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 25.34,
                    fontFamily: 'Roboto',
                    fontWeight: FontWeight.w500,
                    height: 0,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}